# Generated by Django 4.2.14 on 2024-07-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=128, verbose_name='Название'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=128, verbose_name='Название элемента'
                    ),
                ),
                (
                    'menu',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='tree_menu.menu',
                    ),
                ),
                (
                    'parent_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='childrens',
                        to='tree_menu.menuitem',
                    ),
                ),
            ],
        ),
    ]
