# Generated by Django 4.2.14 on 2024-07-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={
                'verbose_name': 'элемент меню',
                'verbose_name_plural': 'Элементы меню',
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='tree_menu.menu',
                verbose_name='Меню',
            ),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='childrens',
                to='tree_menu.menuitem',
                verbose_name='Родительский элемент',
            ),
        ),
    ]
